feature:  ['feat: *', 'feat(*)*: *']
fix:      ['fix: *', 'fix(*)*: *']
docs:     ['docs: *', 'docs(*)*: *']
chore:    ['chore: *', 'chore(*)*: *']
refactor: ['refactor: *', 'refactor(*)*: *']
perf:     ['perf: *', 'perf(*)*: *']
test:     ['test: *', 'test(*)*: *']
ci:       ['build: *', 'build(*)*: *', 'ci: *', 'ci(*)*: *']
style:    ['style: *', 'style(*)*: *']
